/**
 * Generate worker/content.generated.ts — the CV and the assistant's rules, inlined.
 *
 * A worker has no filesystem, so both have to ship inside the bundle. Deriving them here keeps
 * `cv/resume-v*.txt` and `.opencode/agent/bio-guide.md` the only sources: the local proxy reads
 * those files directly, the worker reads this file, and `--check` fails the gate the moment the
 * two drift apart.
 *
 *   bun scripts/chat-worker-build.ts           # write
 *   bun scripts/chat-worker-build.ts --check   # fail if the written file is stale
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { currentResume, agentFile } from './chat-proxy.ts';

const ROOT = resolve(import.meta.dir, '..');
const OUT = `${ROOT}/worker/content.generated.ts`;

/** The agent file is frontmatter plus prose; only the prose is the assistant's rules. */
export function rulesFrom(markdown: string): string {
  const body = markdown.replace(/^---\n[\s\S]*?\n---\n/, '').trim();
  if (!body) throw new Error('agent definition has no body below the frontmatter');
  return body;
}

export function render(cv: string, rules: string, source: string): string {
  return `// GENERATED by scripts/chat-worker-build.ts from ${source} and .opencode/agent/bio-guide.md.
// Do not edit: run \`bun run chat:worker:build\`. \`bun run check:regressions\` fails if this is stale.

export const RULES = ${JSON.stringify(rules)};

export const CV = ${JSON.stringify(cv)};
`;
}

if (import.meta.main) {
  const cvPath = currentResume(ROOT);
  const generated = render(
    readFileSync(cvPath, 'utf8'),
    rulesFrom(readFileSync(agentFile(ROOT), 'utf8')),
    cvPath.replace(`${ROOT}/`, '')
  );

  if (process.argv.includes('--check')) {
    const onDisk = (() => {
      try {
        return readFileSync(OUT, 'utf8');
      } catch {
        return '';
      }
    })();
    if (onDisk !== generated) {
      throw new Error('worker/content.generated.ts is stale — run: bun run chat:worker:build');
    }
    console.log('worker content: in sync with cv/ and the agent definition');
  } else {
    writeFileSync(OUT, generated);
    console.log(`wrote ${OUT.replace(`${ROOT}/`, '')} from ${cvPath.replace(`${ROOT}/`, '')}`);
  }
}
