<!-- SSR omits the widget; it appears only after the browser health probe succeeds. -->
<script>
  import { onMount, tick } from "svelte";
  import { resolveEndpoint, probe, ask } from "$lib/chat.js";

  let endpoint = $state(null);
  let model = $state("");
  let open = $state(false);
  let instant = $state(false);
  let pressed = $state("");
  let busy = $state(false);
  let draft = $state("");
  let error = $state("");
  let messages = $state([]);

  let logEl = $state();
  let inputEl = $state();
  let launcherEl = $state();

  onMount(async () => {
    const url = resolveEndpoint();
    if (!url) return;
    const found = await probe(url);
    if (found === null) return;
    model = found;
    endpoint = url;
  });

  async function toggle(event) {
    instant = event.detail === 0;
    open = !open;
    if (!open) return;
    await tick();
    if (open) inputEl?.focus();
  }

  function press(event, control) {
    if (event.button !== 0 || event.currentTarget.disabled) return;
    instant = false;
    pressed = control;
  }

  function release() {
    pressed = "";
  }

  function onKeydown(event) {
    instant = true;
    release();
    if (event.key === "Escape" && open) {
      open = false;
      launcherEl?.focus();
    }
  }

  async function submit() {
    const question = draft.trim();
    if (!question || busy) return;
    draft = "";
    error = "";
    messages.push({ role: "user", content: question });
    busy = true;
    await scrollLog();
    try {
      const { reply, sig } = await ask(endpoint, $state.snapshot(messages));
      messages.push({ role: "assistant", content: reply, sig });
    } catch (e) {
      error = e.name === "AbortError" ? "The answer took too long." : e.message;
    } finally {
      busy = false;
      await scrollLog();
      if (open) inputEl?.focus();
    }
  }

  async function scrollLog() {
    await tick();
    if (logEl) logEl.scrollTop = logEl.scrollHeight;
  }
</script>

<svelte:window onkeydown={onKeydown} onpointerup={release} onpointercancel={release} onblur={release} />

{#if endpoint}
  <button
    type="button"
    class="chat-fab"
    class:is-open={open}
    class:is-instant={instant}
    class:is-pressed={pressed === "fab"}
    onpointerdown={(event) => press(event, "fab")}
    onpointerleave={release}
    aria-expanded={open}
    aria-controls="chat-panel"
    aria-label={open ? "Close the CV assistant" : "Ask about Fadhlillah's work"}
    bind:this={launcherEl}
    onclick={toggle}
  >
    <svg class="ico" aria-hidden="true"><use href="#i-cpu" /></svg>
  </button>

  <div
    id="chat-panel"
    class="chat-panel"
    class:is-open={open}
    class:is-instant={instant}
    role="dialog"
    aria-label="Ask about Fadhlillah's work"
    aria-hidden={!open}
    inert={!open}
  >
    <header class="chat-bar">
      <span class="chat-dot" aria-hidden="true"></span>
      <span class="chat-title">ask the CV</span>
      <span class="chat-model">{model}</span>
    </header>

    <ol class="chat-log" bind:this={logEl} aria-live="polite" aria-busy={busy}>
      {#if messages.length === 0}
        <li class="chat-msg chat-msg-note">
          Answers are generated by an AI model from the CV on this site and facts already
          published on it, and your questions are sent to a third-party model provider.
          Your IP address is stored for up to 48 hours after your last question to enforce the
          daily question limit. It can be wrong — check anything important against the CV.
        </li>
      {/if}
      {#each messages as message, i (i)}
        <li class="chat-msg chat-msg-{message.role}">
          <span class="chat-who">{message.role === "user" ? "you" : "reply"}</span>
          <p>{message.content}</p>
        </li>
      {/each}
      {#if busy}
        <li class="chat-msg chat-msg-assistant chat-msg-wait">
          <span class="chat-who">reply</span>
          <p>thinking…</p>
        </li>
      {/if}
      {#if error}
        <li class="chat-msg chat-msg-error" role="alert">{error}</li>
      {/if}
    </ol>

    <form class="chat-form" onsubmit={(event) => { event.preventDefault(); submit(); }}>
      <input
        id="chat-input"
        type="text"
        aria-label="Your question"
        autocomplete="off"
        maxlength="2000"
        placeholder="What is your Java experience?"
        bind:value={draft}
        bind:this={inputEl}
        disabled={busy}
      />
      <button
        type="submit"
        class="chat-send"
        class:is-instant={instant}
        class:is-pressed={pressed === "send"}
        onpointerdown={(event) => press(event, "send")}
        onpointerleave={release}
        disabled={busy || !draft.trim()}
      >Ask</button>
    </form>
  </div>
{/if}
